#在哪些世界开启
enable_worlds:
- world
#多少tick尝试执行一次AI
#可以理解为，怪物多长时间防止/摧毁一个方块
#拉高这个值来降低服务器负载
do_ai_ticks: 10
#怪物会放置哪些方块
#最好是标准名称，否则可能无法识别
#所有方块会随机放置
make_blocks:
- DIRT
#哪些怪物会拥有这些AI
#同样的，最好是标准名称，否则可能会无法识别
enable_mob:
- ZOMBIE